/**
 * mock.ts — Tasks module
 * ───────────────────────
 * Mock data for tasks.
 */

import type { Task, TaskColumn } from '@/modules/tasks/types/task';

// ── Task columns ──────────────────────────────────────────────────────────────
export const mockTaskColumns: TaskColumn[] = [
  { id: 'todo', title: 'To Do', color: '#6b7280', order: 0, progress: 0 },
  { id: 'in-progress', title: 'In Progress', color: '#8b5cf6', order: 1, progress: 55 },
  { id: 'review', title: 'Review', color: '#f59e0b', order: 2, progress: 95 },
  { id: 'done', title: 'Done', color: '#22c55e', order: 3, progress: 100, isDone: true },
];

export const tasks: Task[] = [
  {
    id: 'TASK-01',
    title: 'Thiết kế giao diện trang chủ',
    priority: 'High',
    status: 'done',
    sprintId: 'SPRINT-08',
    description: 'Thiết kế màn hình trang chủ theo Figma mockup đã được duyệt, bao gồm hero section, featured products và footer.',
    assigneeId: 'TM-01',
    reporterId: 'TM-04',
    deadline: '05/03/2026',
    startDate: '01/03/2026',
    completedAt: '04/03/2026',
    points: 5,
    order: 0,
    dueDate: new Date('2026-03-05'),
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'TASK-02',
    title: 'Tích hợp API thanh toán VNPay',
    priority: 'High',
    status: 'in-progress',
    sprintId: 'SPRINT-08',
    description: 'Kết nối và xử lý callback từ VNPay gateway. Đảm bảo xử lý đúng các trạng thái: thành công, thất bại, đang xử lý.',
    assigneeId: 'TM-02',
    reporterId: 'TM-05',
    deadline: '20/03/2026',
    startDate: '05/03/2026',
    points: 8,
    order: 1,
    dueDate: new Date('2026-03-20'),
    createdAt: new Date('2026-03-02'),
    updatedAt: new Date('2026-03-02'),
  },
  {
    id: 'TASK-03',
    title: 'Viết unit test cho module giỏ hàng',
    priority: 'Normal',
    status: 'todo',
    sprintId: 'SPRINT-08',
    description: 'Bao phủ các case: thêm sản phẩm, xoá sản phẩm, cập nhật số lượng, tính tổng tiền có áp dụng coupon.',
    assigneeId: 'TM-03',
    reporterId: 'TM-01',
    deadline: '25/03/2026',
    points: 3,
    order: 2,
    dueDate: new Date('2026-03-25'),
    createdAt: new Date('2026-03-03'),
    updatedAt: new Date('2026-03-03'),
  },
  {
    id: 'TASK-04',
    title: 'Tối ưu hiệu năng trang danh sách sản phẩm',
    priority: 'Normal',
    status: 'review',
    sprintId: 'SPRINT-08',
    description: 'Áp dụng virtual scrolling, lazy load ảnh, debounce search và cache kết quả filter. Mục tiêu LCP < 2s.',
    assigneeId: 'TM-01',
    reporterId: 'TM-06',
    deadline: '15/03/2026',
    startDate: '08/03/2026',
    points: 5,
    order: 3,
    dueDate: new Date('2026-03-15'),
    createdAt: new Date('2026-03-04'),
    updatedAt: new Date('2026-03-04'),
  },
  {
    id: 'TASK-05',
    title: 'Xây dựng hệ thống thông báo realtime',
    priority: 'High',
    status: 'in-progress',
    sprintId: 'SPRINT-08',
    description: 'Sử dụng Firebase Realtime Database để push thông báo đơn hàng, khuyến mãi cho người dùng theo thời gian thực.',
    assigneeId: 'TM-04',
    reporterId: 'TM-02',
    deadline: '18/03/2026',
    startDate: '10/03/2026',
    points: 13,
    order: 4,
    dueDate: new Date('2026-03-18'),
    createdAt: new Date('2026-03-05'),
    updatedAt: new Date('2026-03-05'),
  },
  {
    id: 'TASK-06',
    title: 'Cập nhật chính sách bảo mật và cookie',
    priority: 'Low',
    status: 'todo',
    description: 'Rà soát và cập nhật tài liệu chính sách bảo mật theo quy định PDPA 2024. Thêm cookie consent banner.',
    reporterId: 'TM-03',
    order: 5,
    createdAt: new Date('2026-03-06'),
    updatedAt: new Date('2026-03-06'),
  },
  {
    id: 'TASK-07',
    title: 'Sửa lỗi pagination trên mobile',
    priority: 'High',
    status: 'done',
    sprintId: 'SPRINT-08',
    description: 'Bug: nút "trang tiếp theo" bị ẩn trên màn hình nhỏ hơn 375px. Fix responsive và kiểm tra cross-browser.',
    assigneeId: 'TM-02',
    reporterId: 'TM-07',
    deadline: '08/03/2026',
    startDate: '06/03/2026',
    completedAt: '07/03/2026',
    points: 2,
    order: 6,
    dueDate: new Date('2026-03-08'),
    createdAt: new Date('2026-03-07'),
    updatedAt: new Date('2026-03-07'),
  },
  {
    id: 'TASK-08',
    title: 'Thiết lập CI/CD pipeline cho môi trường staging',
    priority: 'Normal',
    status: 'review',
    sprintId: 'SPRINT-08',
    description: 'Cấu hình GitHub Actions để tự động deploy lên Vercel staging khi merge vào nhánh develop.',
    assigneeId: 'TM-07',
    reporterId: 'TM-04',
    deadline: '22/03/2026',
    startDate: '12/03/2026',
    points: 5,
    order: 7,
    dueDate: new Date('2026-03-22'),
    createdAt: new Date('2026-03-08'),
    updatedAt: new Date('2026-03-08'),
  },
  {
    id: 'TASK-09',
    title: 'Nghiên cứu và đề xuất giải pháp SEO',
    priority: 'Low',
    status: 'todo',
    description: 'Phân tích hiện trạng SEO, đề xuất cải thiện metadata, sitemap, structured data và Core Web Vitals.',
    assigneeId: 'TM-04',
    reporterId: 'TM-01',
    order: 8,
    createdAt: new Date('2026-03-09'),
    updatedAt: new Date('2026-03-09'),
  },
  {
    id: 'TASK-10',
    title: 'Triển khai tính năng so sánh sản phẩm',
    priority: 'Normal',
    status: 'todo',
    description: 'Cho phép người dùng chọn tối đa 4 sản phẩm để so sánh thông số kỹ thuật, giá và đánh giá.',
    assigneeId: 'TM-01',
    reporterId: 'TM-03',
    deadline: '30/03/2026',
    points: 8,
    order: 9,
    dueDate: new Date('2026-03-30'),
    createdAt: new Date('2026-03-10'),
    updatedAt: new Date('2026-03-10'),
  },
];
