import type { Comment } from './types/comment';

export const comments: Comment[] = [
  // ── TASK-01 threads ─────────────────────────────────────────────────────────
  {
    id: 'CMT-001',
    entityType: 'task',
    entityId: 'TASK-01',
    authorId: 'TM-01',
    authorName: 'Anh Nguyễn',
    authorInitials: 'AN',
    authorGradient: 'linear-gradient(135deg,#6c63ff,#a855f7)',
    content: 'Đã xem xét yêu cầu. Cần làm rõ phần validation form trước khi bắt đầu, spec hiện tại còn mơ hồ.',
    createdAt: '2026-03-10T09:00:00.000Z',
  },
  {
    id: 'CMT-002',
    entityType: 'task',
    entityId: 'TASK-01',
    authorId: 'TM-02',
    authorName: 'Bảo Trần',
    authorInitials: 'BT',
    authorGradient: 'linear-gradient(135deg,#22c55e,#16a34a)',
    content: 'Đồng ý. Tôi đã hỏi PM và họ sẽ cập nhật doc vào ngày mai. Tạm thời dùng rule: required + max 255 chars.',
    createdAt: '2026-03-10T09:45:00.000Z',
    parentId: 'CMT-001',
  },
  {
    id: 'CMT-003',
    entityType: 'task',
    entityId: 'TASK-01',
    authorId: 'TM-05',
    authorName: 'Ema Vũ',
    authorInitials: 'EV',
    authorGradient: 'linear-gradient(135deg,#06b6d4,#0891b2)',
    content: 'UI mockup đã upload lên Figma. Link trong description của task. Cần chú ý spacing trên mobile.',
    createdAt: '2026-03-11T08:20:00.000Z',
  },
  {
    id: 'CMT-004',
    entityType: 'task',
    entityId: 'TASK-01',
    authorId: 'TM-01',
    authorName: 'Anh Nguyễn',
    authorInitials: 'AN',
    authorGradient: 'linear-gradient(135deg,#6c63ff,#a855f7)',
    content: 'Đã xem Figma, design ổn. Sẽ implement theo breakpoint 375px. Cảm ơn Ema!',
    createdAt: '2026-03-11T09:05:00.000Z',
    parentId: 'CMT-003',
  },

  // ── TASK-02 threads ─────────────────────────────────────────────────────────
  {
    id: 'CMT-005',
    entityType: 'task',
    entityId: 'TASK-02',
    authorId: 'TM-03',
    authorName: 'Chi Hoàng',
    authorInitials: 'CH',
    authorGradient: 'linear-gradient(135deg,#f59e0b,#d97706)',
    content: 'Task này block sprint goal. Cần prioritize và xử lý trước cuối tuần.',
    createdAt: '2026-03-12T10:30:00.000Z',
  },
  {
    id: 'CMT-006',
    entityType: 'task',
    entityId: 'TASK-02',
    authorId: 'TM-06',
    authorName: 'Phong Ngô',
    authorInitials: 'FN',
    authorGradient: 'linear-gradient(135deg,#a855f7,#7c3aed)',
    content: 'Test case đã viết xong, waiting for implementation. Ping tôi khi code xong để review.',
    createdAt: '2026-03-12T11:00:00.000Z',
    parentId: 'CMT-005',
  },

  // ── BUG-001 threads ─────────────────────────────────────────────────────────
  {
    id: 'CMT-007',
    entityType: 'bug',
    entityId: 'BUG-001',
    authorId: 'TM-04',
    authorName: 'Duy Lê',
    authorInitials: 'DL',
    authorGradient: 'linear-gradient(135deg,#ec4899,#be185d)',
    content: 'Root cause: payment gateway callback không return đúng status code. Backend đang xử lý response sai.',
    createdAt: '2026-03-13T14:00:00.000Z',
  },
  {
    id: 'CMT-008',
    entityType: 'bug',
    entityId: 'BUG-001',
    authorId: 'TM-02',
    authorName: 'Bảo Trần',
    authorInitials: 'BT',
    authorGradient: 'linear-gradient(135deg,#22c55e,#16a34a)',
    content: 'Confirm root cause đúng. Hotfix branch đã tạo: hotfix/payment-callback-status. Review PR nhé.',
    createdAt: '2026-03-13T15:30:00.000Z',
    parentId: 'CMT-007',
  },
  {
    id: 'CMT-009',
    entityType: 'bug',
    entityId: 'BUG-001',
    authorId: 'TM-01',
    authorName: 'Anh Nguyễn',
    authorInitials: 'AN',
    authorGradient: 'linear-gradient(135deg,#6c63ff,#a855f7)',
    content: 'Frontend cần update loading state để UX không bị blank screen trong lúc chờ. Tôi sẽ xử lý song song.',
    createdAt: '2026-03-13T16:00:00.000Z',
    parentId: 'CMT-007',
  },

  // ── BUG-003 threads ─────────────────────────────────────────────────────────
  {
    id: 'CMT-010',
    entityType: 'bug',
    entityId: 'BUG-003',
    authorId: 'TM-06',
    authorName: 'Phong Ngô',
    authorInitials: 'FN',
    authorGradient: 'linear-gradient(135deg,#a855f7,#7c3aed)',
    content: 'Reproduced. Lỗi xảy ra khi category ID bị overlap giữa Electronics (cat_01) và Clothing (cat_11). SQL query dùng LIKE thay vì exact match.',
    createdAt: '2026-03-14T09:15:00.000Z',
  },
  {
    id: 'CMT-011',
    entityType: 'bug',
    entityId: 'BUG-003',
    authorId: 'TM-02',
    authorName: 'Bảo Trần',
    authorInitials: 'BT',
    authorGradient: 'linear-gradient(135deg,#22c55e,#16a34a)',
    content: 'Fix đơn giản: thay LIKE "%cat_01%" bằng = "cat_01". Đã push commit, test lại giúp với.',
    createdAt: '2026-03-14T10:00:00.000Z',
    parentId: 'CMT-010',
  },
  {
    id: 'CMT-012',
    entityType: 'bug',
    entityId: 'BUG-003',
    authorId: 'TM-06',
    authorName: 'Phong Ngô',
    authorInitials: 'FN',
    authorGradient: 'linear-gradient(135deg,#a855f7,#7c3aed)',
    content: 'Tested ✓. Filter giờ đúng với tất cả categories. Marking In Review.',
    createdAt: '2026-03-14T11:30:00.000Z',
    parentId: 'CMT-010',
  },
];
