import type { Bug, BugColumn } from '@/modules/bugs/types/bug';

// ── Bug columns ──────────────────────────────────────────────────────────────
export const mockBugColumns: BugColumn[] = [
  { id: 'open', title: 'Open', color: '#ef4444', order: 0 },
  { id: 'in-progress', title: 'In Progress', color: '#8b5cf6', order: 1 },
  { id: 'in-review', title: 'In Review', color: '#f59e0b', order: 2 },
  { id: 'fixed', title: 'Fixed', color: '#22c55e', order: 3 },
  { id: 'wont-fix', title: "Won't Fix", color: '#64748b', order: 4 },
];

// ── Bugs ─────────────────────────────────────────────────────────────────────
export const bugs: Bug[] = [
  {
    id: 'BUG-001',
    title: 'Trang thanh toán bị trắng sau khi submit form',
    severity: 'Critical',
    status: 'open',
    description: 'Người dùng nhấn "Thanh toán" thì trang trở nên trắng, không có phản hồi hay thông báo lỗi.',
    stepsToReproduce: '1. Vào giỏ hàng\n2. Nhấn Thanh toán\n3. Điền thông tin thẻ\n4. Submit',
    assigneeId: 'TM-01',
    reporterId: 'TM-05',
    order: 0,
    reportedAt: '2025-01-10',
    deadline: '2025-01-20',
  },
  {
    id: 'BUG-002',
    title: 'Avatar người dùng không load trên mobile Safari',
    severity: 'High',
    status: 'in-progress',
    description: 'Avatar hiển thị broken image trên Safari iOS 16+. Chrome và Firefox không bị.',
    stepsToReproduce: '1. Mở app trên iPhone Safari\n2. Vào profile\n3. Thấy broken image',
    assigneeId: 'TM-03',
    reporterId: 'TM-06',
    order: 1,
    startDate: '2025-01-13',
    reportedAt: '2025-01-12',
    deadline: '2025-01-22',
  },
  {
    id: 'BUG-003',
    title: 'Filter theo category trả về kết quả sai',
    severity: 'High',
    status: 'in-review',
    description: 'Khi filter "Electronics", hệ thống hiển thị cả sản phẩm từ category "Clothing".',
    stepsToReproduce: '1. Vào trang Products\n2. Chọn filter Electronics\n3. Xem kết quả',
    assigneeId: 'TM-02',
    reporterId: 'TM-04',
    order: 2,
    startDate: '2025-01-09',
    reportedAt: '2025-01-08',
    deadline: '2025-01-18',
  },
  {
    id: 'BUG-004',
    title: 'Email xác nhận đơn hàng gửi trùng 2 lần',
    severity: 'Medium',
    status: 'fixed',
    description: 'Sau khi đặt hàng thành công, hệ thống gửi email xác nhận 2 lần cho cùng một đơn.',
    stepsToReproduce: '1. Đặt hàng\n2. Kiểm tra inbox',
    assigneeId: 'TM-04',
    reporterId: 'TM-07',
    order: 3,
    startDate: '2025-01-07',
    reportedAt: '2025-01-05',
    resolvedAt: '2025-01-15',
    completedAt: '2025-01-16',
  },
  {
    id: 'BUG-005',
    title: 'Nút "Thêm vào giỏ" bị disabled sau khi reload',
    severity: 'Medium',
    status: 'open',
    description: 'Reload trang product detail thì nút "Thêm vào giỏ" bị disabled dù còn hàng.',
    stepsToReproduce: '1. Vào trang sản phẩm\n2. Reload (F5)\n3. Thấy nút bị disabled',
    assigneeId: 'TM-01',
    reporterId: 'TM-03',
    order: 4,
    reportedAt: '2025-01-14',
    deadline: '2025-01-24',
  },
  {
    id: 'BUG-006',
    title: 'Số lượng tồn kho hiển thị âm sau flash sale',
    severity: 'Critical',
    status: 'fixed',
    description: 'Sau flash sale, một số sản phẩm hiển thị tồn kho âm (-3, -7). Cần validate server side.',
    stepsToReproduce: '1. Tổ chức flash sale\n2. Quan sát inventory sau khi kết thúc',
    assigneeId: 'TM-05',
    reporterId: 'TM-01',
    order: 5,
    startDate: '2025-01-04',
    reportedAt: '2025-01-03',
    resolvedAt: '2025-01-09',
    completedAt: '2025-01-10',
  },
  {
    id: 'BUG-007',
    title: 'Tìm kiếm không nhận dấu tiếng Việt',
    severity: 'Low',
    status: 'wont-fix',
    description: 'Tìm "áo" không ra kết quả, nhưng "ao" thì có. Scope hiện tại chỉ hỗ trợ không dấu.',
    stepsToReproduce: '1. Gõ từ có dấu vào ô tìm kiếm',
    assigneeId: 'TM-02',
    reporterId: 'TM-02',
    order: 6,
    reportedAt: '2025-01-06',
  },
  {
    id: 'BUG-008',
    title: 'Tooltip trên chart bị tràn ra ngoài màn hình nhỏ',
    severity: 'Low',
    status: 'in-progress',
    description: 'Trên màn hình 320px, tooltip của biểu đồ doanh thu bị tràn ra ngoài viewport bên phải.',
    stepsToReproduce: '1. Thu nhỏ cửa sổ về 320px\n2. Hover vào chart',
    assigneeId: 'TM-03',
    reporterId: 'TM-05',
    order: 7,
    startDate: '2025-01-17',
    reportedAt: '2025-01-16',
    deadline: '2025-01-28',
  },
  {
    id: 'BUG-009',
    title: 'Session timeout quá ngắn, logout sau 5 phút idle',
    severity: 'Medium',
    status: 'in-review',
    description: 'Config session timeout là 30 phút nhưng thực tế bị logout sau ~5 phút không thao tác.',
    stepsToReproduce: '1. Đăng nhập\n2. Không thao tác 5 phút\n3. Bị logout',
    assigneeId: 'TM-06',
    reporterId: 'TM-04',
    order: 8,
    startDate: '2025-01-12',
    reportedAt: '2025-01-11',
    deadline: '2025-01-25',
  },
  {
    id: 'BUG-010',
    title: 'Import CSV báo lỗi với file có BOM encoding',
    severity: 'High',
    status: 'open',
    description: 'File CSV xuất từ Excel (UTF-8 BOM) bị từ chối khi import sản phẩm hàng loạt.',
    stepsToReproduce: '1. Tạo CSV từ Excel (UTF-8 với BOM)\n2. Import qua tính năng bulk upload',
    assigneeId: 'TM-07',
    reporterId: 'TM-06',
    order: 9,
    reportedAt: '2025-01-17',
    deadline: '2025-01-27',
  },
];
