/**
 * mock.ts — Backlog module
 * ───────────────────────
 * Mock data for epics + embedded user stories.
 */

import type { Epic } from '@/modules/backlog/types/backlog';

export const epics: Epic[] = [
  {
    id: 'EP-01',
    name: 'Quản lý sản phẩm & Danh mục',
    icon: '📦',
    priority: 'High',
    status: 'In Progress',
    startDate: '01/01/2025',
    dueDate: '31/03/2025',
    description: 'Xây dựng hệ thống quản lý sản phẩm hoàn chỉnh, bao gồm danh mục, tồn kho và hiển thị trên giao diện người dùng.',
    goals: 'Người dùng có thể duyệt, tìm kiếm và xem chi tiết sản phẩm. Admin có thể quản lý toàn bộ danh mục và tồn kho từ dashboard.',
    itemCount: 5,
    storyPoints: 31,
    items: [
      {
        id: 'US-001', label: 'Xem danh sách sản phẩm với phân trang',
        status: 'Done', priority: 'High', points: 5,
        startDate: '01/01/2025', dueDate: '10/01/2025',
        assigneeId: 'TM-03',
        description: 'Hiển thị danh sách sản phẩm dạng grid/list với phân trang (20 items/trang).',
        goals: 'Người dùng có thể duyệt qua toàn bộ sản phẩm mà không bị chậm trang.',
      },
      {
        id: 'US-002', label: 'Tìm kiếm & lọc sản phẩm theo danh mục',
        status: 'Done', priority: 'High', points: 8,
        startDate: '10/01/2025', dueDate: '25/01/2025',
        assigneeId: 'TM-03',
        description: 'Thanh tìm kiếm full-text và bộ lọc đa điều kiện (danh mục, giá, thương hiệu).',
        goals: 'Người dùng tìm được sản phẩm cần trong vòng 3 thao tác.',
      },
      {
        id: 'US-003', label: 'Xem chi tiết sản phẩm và ảnh gallery',
        status: 'In Progress', priority: 'Normal', points: 5,
        startDate: '25/01/2025', dueDate: '10/02/2025',
        assigneeId: 'TM-04',
        description: 'Trang chi tiết sản phẩm với gallery ảnh, mô tả, thông số kỹ thuật và đánh giá.',
        goals: 'Người dùng có đủ thông tin để quyết định mua hàng mà không cần rời trang.',
      },
      {
        id: 'US-004', label: 'Thêm/sửa/xóa sản phẩm (Admin)',
        status: 'Todo', priority: 'High', points: 8,
        startDate: '10/02/2025', dueDate: '28/02/2025',
        assigneeId: 'TM-02',
        description: 'Form CRUD sản phẩm cho admin: tên, mô tả, giá, tồn kho, ảnh, danh mục.',
        goals: 'Admin quản lý toàn bộ catalog mà không cần can thiệp kỹ thuật.',
      },
      {
        id: 'US-005', label: 'Quản lý tồn kho và cảnh báo hết hàng',
        status: 'Todo', priority: 'Normal', points: 5,
        startDate: '01/03/2025', dueDate: '20/03/2025',
        assigneeId: 'TM-02',
        description: 'Tracking số lượng tồn kho, tự động cảnh báo khi dưới ngưỡng tối thiểu.',
        goals: 'Admin luôn được thông báo kịp thời khi cần nhập hàng để tránh out-of-stock.',
      },
    ],
  },
  {
    id: 'EP-02',
    name: 'Giỏ hàng & Thanh toán',
    icon: '💳',
    priority: 'High',
    status: 'In Progress',
    startDate: '01/02/2025',
    dueDate: '30/04/2025',
    description: 'Luồng mua hàng từ giỏ hàng đến thanh toán, tích hợp cổng thanh toán VNPAY và xác nhận đơn hàng tự động.',
    goals: 'Người dùng có thể thêm sản phẩm vào giỏ, áp dụng coupon, thanh toán online và nhận xác nhận đơn hàng qua email.',
    itemCount: 4,
    storyPoints: 29,
    items: [
      {
        id: 'US-006', label: 'Thêm sản phẩm vào giỏ hàng',
        status: 'Done', priority: 'High', points: 3,
        startDate: '01/02/2025', dueDate: '08/02/2025',
        assigneeId: 'TM-05',
        description: 'Nút "Thêm vào giỏ" trên trang danh sách và chi tiết, cập nhật badge số lượng trên icon giỏ.',
        goals: 'Người dùng thêm sản phẩm vào giỏ trong 1 click, không cần tải lại trang.',
      },
      {
        id: 'US-007', label: 'Tính tổng tiền và áp dụng coupon',
        status: 'In Progress', priority: 'Normal', points: 8,
        startDate: '08/02/2025', dueDate: '28/02/2025',
        assigneeId: 'TM-05',
        description: 'Trang giỏ hàng: hiển thị subtotal, phí ship, discount và total. Input nhập mã coupon.',
        goals: 'Người dùng thấy rõ tổng chi phí trước khi checkout, coupon áp dụng real-time.',
      },
      {
        id: 'US-008', label: 'Tích hợp cổng thanh toán VNPAY',
        status: 'Todo', priority: 'High', points: 13,
        startDate: '01/03/2025', dueDate: '31/03/2025',
        assigneeId: 'TM-07',
        description: 'Redirect sang VNPAY payment gateway, xử lý IPN callback, lưu transaction log.',
        goals: 'Tỷ lệ thanh toán thành công ≥ 95%, log đầy đủ để đối soát với VNPAY.',
      },
      {
        id: 'US-009', label: 'Xử lý callback và xác nhận đơn hàng',
        status: 'Todo', priority: 'High', points: 5,
        startDate: '01/04/2025', dueDate: '20/04/2025',
        assigneeId: 'TM-07',
        description: 'Nhận callback từ VNPAY, cập nhật trạng thái đơn hàng, gửi email xác nhận cho khách.',
        goals: 'Khách hàng nhận email xác nhận trong vòng 2 phút sau thanh toán thành công.',
      },
    ],
  },
  {
    id: 'EP-03',
    name: 'Xác thực & Hồ sơ người dùng',
    icon: '👤',
    priority: 'Normal',
    status: 'Done',
    startDate: '01/12/2024',
    dueDate: '15/01/2025',
    description: 'Hệ thống xác thực người dùng với email và Google OAuth, quản lý hồ sơ và lịch sử hoạt động.',
    goals: 'Người dùng có thể đăng ký, đăng nhập bằng email hoặc Google, cập nhật hồ sơ và xem lịch sử đơn hàng của mình.',
    itemCount: 4,
    storyPoints: 18,
    items: [
      {
        id: 'US-010', label: 'Đăng ký / Đăng nhập với email',
        status: 'Done', priority: 'High', points: 5,
        startDate: '01/12/2024', dueDate: '15/12/2024',
        assigneeId: 'TM-01',
        description: 'Form đăng ký (email, mật khẩu, tên), đăng nhập, quên mật khẩu via email reset.',
        goals: 'Người dùng tạo tài khoản và đăng nhập trong dưới 2 phút.',
      },
      {
        id: 'US-011', label: 'Đăng nhập với Google OAuth',
        status: 'Done', priority: 'Normal', points: 3,
        startDate: '15/12/2024', dueDate: '22/12/2024',
        description: 'Nút "Đăng nhập với Google" dùng Firebase Auth Google provider.',
        goals: 'Người dùng có Google account đăng nhập bằng 1 click mà không cần tạo mật khẩu.',
      },
      {
        id: 'US-012', label: 'Quản lý địa chỉ giao hàng',
        status: 'Done', priority: 'Normal', points: 5,
        startDate: '22/12/2024', dueDate: '31/12/2024',
        description: 'Thêm/sửa/xóa địa chỉ giao hàng, đặt địa chỉ mặc định cho checkout nhanh.',
        goals: 'Khách hàng thường xuyên không cần nhập lại địa chỉ mỗi lần đặt hàng.',
      },
      {
        id: 'US-013', label: 'Lịch sử đơn hàng',
        status: 'Done', priority: 'Low', points: 5,
        startDate: '01/01/2025', dueDate: '10/01/2025',
        description: 'Trang "Đơn hàng của tôi" hiển thị danh sách đơn hàng, trạng thái và chi tiết.',
        goals: 'Khách hàng tự tra cứu tình trạng đơn hàng mà không cần liên hệ support.',
      },
    ],
  },
  {
    id: 'EP-04',
    name: 'Vận chuyển & Theo dõi đơn hàng',
    icon: '🚚',
    priority: 'Normal',
    status: 'Planning',
    startDate: '01/04/2025',
    dueDate: '30/06/2025',
    description: 'Tích hợp API các đơn vị vận chuyển (GHN, GHTK), tính phí ship tự động và cung cấp tracking đơn hàng real-time cho khách hàng.',
    goals: 'Hệ thống tự động tính phí vận chuyển theo địa chỉ, cập nhật trạng thái đơn hàng real-time và gửi thông báo đến khách khi có thay đổi.',
    itemCount: 4,
    storyPoints: 26,
    items: [
      {
        id: 'US-014', label: 'Tính phí vận chuyển theo địa chỉ',
        status: 'Todo', priority: 'High', points: 8,
        startDate: '01/04/2025', dueDate: '20/04/2025',
        description: 'Gọi API GHN/GHTK để tính phí ship dựa trên địa chỉ người gửi/nhận và khối lượng đơn.',
        goals: 'Phí ship hiển thị chính xác tại bước checkout, không có chênh lệch sau khi đặt hàng.',
      },
      {
        id: 'US-015', label: 'Tích hợp API đơn vị vận chuyển (GHN, GHTK)',
        status: 'Todo', priority: 'High', points: 13,
        startDate: '20/04/2025', dueDate: '31/05/2025',
        description: 'Tạo đơn vận chuyển tự động sau khi thanh toán thành công, nhận webhook cập nhật trạng thái.',
        goals: 'Toàn bộ quy trình từ thanh toán đến giao hàng tự động, không cần can thiệp thủ công.',
      },
      {
        id: 'US-016', label: 'Theo dõi trạng thái đơn hàng real-time',
        status: 'Todo', priority: 'Normal', points: 3,
        startDate: '01/06/2025', dueDate: '15/06/2025',
        description: 'Trang tracking hiển thị timeline trạng thái đơn hàng từ kho đến tay khách.',
        goals: 'Khách hàng biết chính xác đơn hàng đang ở đâu mà không cần gọi điện.',
      },
      {
        id: 'US-017', label: 'Thông báo email khi đơn hàng thay đổi trạng thái',
        status: 'Todo', priority: 'Low', points: 2,
        startDate: '15/06/2025', dueDate: '25/06/2025',
        description: 'Gửi email tự động khi đơn hàng chuyển sang các mốc: đã lấy hàng, đang vận chuyển, đã giao.',
        goals: 'Khách hàng chủ động được thông báo, giảm câu hỏi "đơn hàng tôi đến đâu rồi?".',
      },
    ],
  },
  {
    id: 'EP-05',
    name: 'Báo cáo & Phân tích',
    icon: '📊',
    priority: 'Low',
    status: 'Planning',
    startDate: '01/06/2025',
    dueDate: '31/08/2025',
    description: 'Dashboard phân tích doanh thu, sản phẩm bán chạy và hành vi người dùng. Hỗ trợ xuất báo cáo ra Excel.',
    goals: 'Admin có thể xem báo cáo doanh thu theo ngày/tháng, phân tích sản phẩm bán chạy và xuất dữ liệu để báo cáo nội bộ.',
    itemCount: 3,
    storyPoints: 18,
    items: [
      {
        id: 'US-018', label: 'Dashboard doanh thu theo ngày / tháng',
        status: 'Todo', priority: 'Normal', points: 8,
        startDate: '01/06/2025', dueDate: '30/06/2025',
        description: 'Biểu đồ line/bar hiển thị doanh thu theo ngày và tháng, so sánh với kỳ trước.',
        goals: 'Admin nắm được xu hướng doanh thu trong 5 giây khi mở dashboard.',
      },
      {
        id: 'US-019', label: 'Báo cáo sản phẩm bán chạy',
        status: 'Todo', priority: 'Normal', points: 5,
        startDate: '01/07/2025', dueDate: '20/07/2025',
        description: 'Bảng top sản phẩm bán chạy nhất theo lượt bán và doanh thu, lọc theo khoảng thời gian.',
        goals: 'Team mua hàng biết sản phẩm nào cần nhập thêm để đáp ứng nhu cầu.',
      },
      {
        id: 'US-020', label: 'Xuất báo cáo ra file Excel',
        status: 'Todo', priority: 'Low', points: 5,
        startDate: '20/07/2025', dueDate: '10/08/2025',
        description: 'Nút export để tải xuống báo cáo dưới dạng .xlsx với định dạng chuẩn.',
        goals: 'Ban quản lý có thể chia sẻ số liệu qua file Excel mà không cần developer hỗ trợ.',
      },
    ],
  },
];
