import type { Project } from '@/modules/projects/types/project';

export const mockProjects: Project[] = [
  {
    id: 'default',
    name: 'E-Commerce Platform',
    description: 'Nền tảng thương mại điện tử toàn diện với tích hợp thanh toán, quản lý kho, và hệ thống khuyến mãi.',
    status: 'active',
    icon: '🛒',
    color: 'from-violet-500 to-purple-600',
    currentSprint: 'Sprint 7',
    quarter: 'Q1 2025',
    startDate: '2024-07-01',
    endDate: '2025-06-30',
    techStack: ['Next.js', 'Node.js', 'PostgreSQL', 'Redis'],
    teamSize: 8,
    createdAt: '2024-07-01',
  },
  {
    id: 'hrm',
    name: 'HRM System',
    description: 'Hệ thống quản lý nhân sự tích hợp chấm công, tính lương, và đánh giá hiệu suất nhân viên.',
    status: 'active',
    icon: '👥',
    color: 'from-blue-500 to-cyan-600',
    currentSprint: 'Sprint 3',
    quarter: 'Q2 2025',
    startDate: '2025-01-15',
    endDate: '2025-12-31',
    techStack: ['React', 'FastAPI', 'MySQL', 'Elasticsearch'],
    teamSize: 5,
    createdAt: '2025-01-15',
  },
  {
    id: 'ebanking',
    name: 'Mobile Banking App',
    description: 'Ứng dụng ngân hàng di động với tính năng chuyển tiền, quản lý tài khoản, và xác thực sinh trắc học.',
    status: 'active',
    icon: '🏦',
    color: 'from-emerald-500 to-green-600',
    currentSprint: 'Sprint 1',
    quarter: 'Q2 2025',
    startDate: '2025-03-01',
    endDate: '2025-09-30',
    techStack: ['React Native', 'Go', 'MongoDB', 'Kafka'],
    teamSize: 10,
    createdAt: '2025-03-01',
  },
];
